PropType
wbobeirne/nycda-basic-react pull request #7
Opened 2017-07-23 16:41 UTC by xcatlkd

Added a type check to Title.js.
Checks if the type of the props.children attribute is a number.
Obviously super useful, but does throw an error in the console if another type is passed.

2017-07-23 16:48 UTC, wbobeirne commented
Nice work. But maybe you could make it useful by using it on your Font class? Size should always be a number, but color should always be a string.

2017-07-23 17:19 UTC, wbobeirne requested changes
Try to put the prop types on Font for the right requirements

2017-07-23 17:52 UTC, xcatlkd commented
That is a more reasonable use case.

2017-07-23 18:01 UTC, xcatlkd commented
Code updated. Changes made to Font.js to check PropTypes on both color (string) and size (number).

2017-07-23 20:43 UTC, wbobeirne requested changes

2017-07-23 20:43 UTC, wbobeirne commented on js/components/Font.js
> +};
Title would be undefined here, I think you want Font.

2017-07-24 01:05 UTC, xcatlkd commented
Should work now.

2017-07-25 23:27 UTC, wbobeirne approved these changes
LGTM 👍

2017-07-25 23:27 UTC, closed without merging